# Generated by Django 5.1.2 on 2024-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rolls',
            field=models.IntegerField(default=0),
        ),
    ]
